[tool.poetry]
name = "impartlogbot"
version = "0.1.0"
description = ""
authors = ["Skimige <me@xyx.moe>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Pyrogram = "^2.0.97"
TgCrypto = "^1.2.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
